name: New Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.comment.user.id }} != 63413175
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Create Zeebe Workflow
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: publishMessage
          messageName: new comment
          correlationKey: ${{ github.event.issue.number }}
          variables: '{"comment": ${{ toJson(github.event.comment) }}, "issue": ${{ toJson(github.event.issue) }} }'
          timeToLive: Duration.minutes.of(10)
